artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://www.kaggle.com/datasets/phucthaiv02/butterfly-image-classification/data
  local_data_file: artifacts/data_ingestion

data_preparation:
  root_path: artifacts/data_preparation
  train_csv_path: artifacts/data_ingestion/butterfly-image-classification/Training_set.csv
  test_csv_path: artifacts/data_ingestion/butterfly-image-classification/Testing_set.csv
  train_images_path: artifacts/data_ingestion/butterfly-image-classification/train
  test_images_path: artifacts/data_ingestion/butterfly-image-classification/test
  train_output_image_path: artifacts/data_preparation/train
  validation_output_image_path: artifacts/data_preparation/validation
  train_output_csv_path: artifacts/data_preparation/train.csv
  validation_output_csv_path: artifacts/data_preparation/validation.csv

train:
  model_root_dir: artifacts/models
  trained_model_path: artifacts/models/model.pth